# =============================================
#   Smart Bank Queue - Application Properties
# =============================================

# Server
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bank_queue?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Niki@2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =============================================
#   Email Notification Configuration
#   Set notification.enabled=true and fill
#   in your Gmail credentials to enable emails
# =============================================
notification.enabled=false

# Gmail SMTP (uncomment and fill to enable)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=nikithasenthilnathan1234@gmail.com
#spring.mail.password=qfagemxhfujrwhiw
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
logging.level.com.smartqueue=DEBUG
logging.level.org.springframework.web=INFO